<a href="https://colab.research.google.com/github/Darielle-Angela-Valero/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# Problem 1

import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1,2],
              [3,4],
              [5,6]])

C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

D = np.array([[1, 2],
              [3, 4]])

AB = np.dot(A,B)
print("a.) AB:")
print(AB)

DD = D + D
print("\n b.) D + D:")
print(DD)

s = 2
twoC = s*C
print("\nC.) 2C:")
print(twoC)


a.) AB:
[[22 28]
 [49 64]]

 b.) D + D:
[[2 4]
 [6 8]]

C.) 2C:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [8]:
# Problem 2  Find the cross-product of matrices, A = [2,7,4] and B = [3,9,8]. Show your solutions using Python program.
import numpy as np
A = np.array([2, 7, 4])
B = np.array([3, 9, 8])
product = np.cross(A, B)
print("Product:")
print(product)


Product:
[20 -4 -3]
