<a href="https://colab.research.google.com/github/Darielle-Angela-Valero/58013-Linear-Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Question 1. (20 points) Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.
import numpy as np
numbers = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8],
              [9,10]])
one = 1
onechart = one*numbers
print("By 1:\n", onechart)

two = 2
twochart = two*numbers
print("By 2:\n", twochart)

three = 3
threechart = three*numbers
print("By 3:\n", threechart)

four = 4
fourchart = four*numbers
print("By 4:\n", fourchart)

five = 5
fivechart = five*numbers
print("By 5:\n", fivechart)

six = 6
sixchart = six*numbers
print("By 6:\n", sixchart)

seven = 7
sevenchart = seven*numbers
print("By 7:\n", sevenchart)

eight = 8
eightchart = eight*numbers
print("By 8:\n", eightchart)

nine = 9
ninechart = nine*numbers
print("By 9:\n", ninechart)

ten = 10
tenchart = ten*numbers
print("By 10:\n", tenchart)


By 1:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
By 2:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
By 3:
 [[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]
By 4:
 [[ 4  8]
 [12 16]
 [20 24]
 [28 32]
 [36 40]]
By 5:
 [[ 5 10]
 [15 20]
 [25 30]
 [35 40]
 [45 50]]
By 6:
 [[ 6 12]
 [18 24]
 [30 36]
 [42 48]
 [54 60]]
By 7:
 [[ 7 14]
 [21 28]
 [35 42]
 [49 56]
 [63 70]]
By 8:
 [[ 8 16]
 [24 32]
 [40 48]
 [56 64]
 [72 80]]
By 9:
 [[ 9 18]
 [27 36]
 [45 54]
 [63 72]
 [81 90]]
By 10:
 [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]


In [5]:
# Question 2. (10 points) In relation to Question 1, show a solution that doubles all the values of each element.
import numpy as np
numbers = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8],
              [9,10]])

one = 1
onechart = one*numbers
oneD = onechart*2
print("Double Values of 1:\n", oneD)

two = 2
twochart = two*numbers
twoD = twochart*2
print("Double Values of 2:\n", twoD)


three = 3
threechart = three*numbers
threeD = threechart*2
print("Double Values of 3:\n", threeD)


four = 4
fourchart = four*numbers
fourD = fourchart*2
print("Double Values of 4:\n", fourD)


five = 5
fivechart = five*numbers
fiveD = fivechart*2
print("Double Values of 5:\n", fiveD)


six = 6
sixchart = six*numbers
sixD = sixchart*2
print("Double Values of 6:\n", sixD)


seven = 7
sevenchart = seven*numbers
sevD = sevenchart*2
print("Double Values of 7:\n", sevD)


eight = 8
eightchart = eight*numbers
eytD = eightchart*2
print("Double Values of 8:\n", eytD)

nine = 9
ninechart = nine*numbers
nineD = ninechart*2
print("Double Values of 9:\n", nineD)

ten = 10
tenchart = ten*numbers
tenD = tenchart*2
print("Double Values of 10:\n", tenD)



Double Values of 1:
 [[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
Double Values of 2:
 [[ 4  8]
 [12 16]
 [20 24]
 [28 32]
 [36 40]]
Double Values of 3:
 [[ 6 12]
 [18 24]
 [30 36]
 [42 48]
 [54 60]]
Double Values of 4:
 [[ 8 16]
 [24 32]
 [40 48]
 [56 64]
 [72 80]]
Double Values of 5:
 [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]
Double Values of 6:
 [[ 12  24]
 [ 36  48]
 [ 60  72]
 [ 84  96]
 [108 120]]
Double Values of 7:
 [[ 14  28]
 [ 42  56]
 [ 70  84]
 [ 98 112]
 [126 140]]
Double Values of 8:
 [[ 16  32]
 [ 48  64]
 [ 80  96]
 [112 128]
 [144 160]]
Double Values of 9:
 [[ 18  36]
 [ 54  72]
 [ 90 108]
 [126 144]
 [162 180]]
Double Values of 10:
 [[ 20  40]
 [ 60  80]
 [100 120]
 [140 160]
 [180 200]]


In [1]:
# Question 3. (10 points) Create a square matrix that has a diagonal 1's.
import numpy as np
square = np.eye(3,3)
print(square)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# Question 4: Type a python program that can view the size, shape, and dimension of the matrix.
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("Matrix:\n",np.matrix(matrix))
z = np.size(matrix)
print("Size:",z)
y = np.shape(matrix)
print("Shape:",y)
x = np.ndim(matrix)
print("Dimension:",x)





Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Size: 12
Shape: (3, 4)
Dimension: 2


In [6]:
# Question 5: Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.
import numpy as np

arrayOne = np.array([[5,6,9],[21,18,27]])
arrayTwo = np.array([[15,33,24],[4,7,1]])

arraysum = arrayOne + arrayTwo
print("Sum of two NumPy arrays:\n",arraysum)

sqrd = arraysum**2
print("Squared result:\n",sqrd)

Sum of two NumPy arrays:
 [[20 39 33]
 [25 25 28]]
Squared result:
 [[ 400 1521 1089]
 [ 625  625  784]]
