<a href="https://colab.research.google.com/github/Darielle-Angela-Valero/58013-Linear-Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)


-235.0000000000002

Coding Activity 9: Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3,3). In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
#Commutative Property
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

#  A * B
result1 = np.dot(A, B)
print("A*B:\n",result1)

#  B * A
result2 = np.dot(B, A)
print("B*A:\n",result2)

# Check if the results are equal
if np.array_equal(result1, result2):
    print("Matrix multiplication is commutative for 3x3 matrices.")
else:
    print("Matrix multiplication is not commutative for 3x3 matrices.")

A*B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
B*A:
 [[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]
Matrix multiplication is not commutative for 3x3 matrices.


In [ ]:
#Associative Property
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 4, 6],
              [8, 10, 12],
              [3, 6, 9]])

# Calculate (A * B) * C
result1 = np.dot(np.dot(A, B), C)
print("(A*B)*C:\n",result1)

# Calculate A * (B * C)
result2 = np.dot(A, np.dot(B, C))
print(" A*(B*C):\n",result2)

# Check if the results are equal
if np.array_equal(result1, result2):
    print("Matrix multiplication is associative for 3x3 matrices.")
else:
    print("Matrix multiplication is not associative for 3x3 matrices.")

(A*B)*C:
 [[ 306  468  630]
 [ 882 1350 1818]
 [1458 2232 3006]]
 A*(B*C):
 [[ 306  468  630]
 [ 882 1350 1818]
 [1458 2232 3006]]
Matrix multiplication is associative for 3x3 matrices.


In [ ]:
#Distributive Property
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

C = np.array([[2, 4, 6],
              [8, 10, 12],
              [3, 6, 9]])

# A * (B + C)
result1 = np.dot(A, B + C)
print("A*(B + C):\n", result1)

# (A * B) + (A * C)
result2 = np.dot(A, B) + np.dot(A, C)
print("(A * B) + (A * C):\n", result2)

# Check if the results are equal
if np.array_equal(result1, result2):
    print("Matrix multiplication is distributive.")
else:
    print("Matrix multiplication is not distributive.")

A*(B + C):
 [[ 57  66  75]
 [150 171 192]
 [243 276 309]]
(A * B) + (A * C):
 [[ 57  66  75]
 [150 171 192]
 [243 276 309]]
Matrix multiplication is distributive over addition for 3x3 matrices.


In [ ]:
#Identity Property
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

I = np.identity(3)

#  I * A
result1 = np.dot(I,A)
print("I*A:\n", result1)

#  A * I
result2 = np.dot(A,I)
print("A*I:\n",result2)
# Check if the results are equal to A
if np.array_equal(result1, A) and np.array_equal(result2, A):
    print("Identity matrix multiplication property holds for 3x3 matrices.")
else:
    print("Identity matrix multiplication property does not hold for 3x3 matrices.")

I*A:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A*I:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Identity matrix multiplication property holds for 3x3 matrices.


In [2]:
#Zero Property

import numpy as np
# Create two matrices .
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.zeros((3, 3))

# Multiply
result = np.dot(A, B)

print("Matrix A:")
print(A)
print("Zero Matrix B:")
print(B)
print("Result of multiplication that leads to Zero Matrix:")
print(result)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Zero Matrix B:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Result of multiplication that leads to Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
#Dimension Property

import numpy as np
#two matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Multiply
result = np.dot(A, B)

print("Matrix A (3x3):")
print(A)
print("Matrix B (3x3):")
print(B)
print(" A * B (3x3):")
print(result)
print("Resulting matrix dimensions:", result.shape)

Matrix A (3x3):
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B (3x3):
[[9 8 7]
 [6 5 4]
 [3 2 1]]
 A * B (3x3):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Resulting matrix dimensions: (3, 3)
