<a href="https://colab.research.google.com/github/Darielle-Angela-Valero/58013-Linear-Algebra/blob/main/Python_Exercise_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Addition

In [5]:
import numpy as np
#Given vector values
A = np.array([[-0.4],[4.3],[-0.6]]) #column vector
B = np.array([[-0.2,0.2,1]]) # 1x2 array
C = np.array([[-0.2,2.1,-1.5]]) # 1x3 array
sum = A + B + C
print("Sum:\n", sum)


Sum:
 [[-0.8  1.9 -0.9]
 [ 3.9  6.6  3.8]
 [-1.   1.7 -1.1]]


Vector Subtraction


In [6]:
import numpy as np
#Given vector values
A = np.array([[-0.4],[4.3],[-0.6]]) # 3x1 column vector
B = np.array([[-0.2,0.2,1]]) # 1x2 array
C = np.array([[-0.2,2.1,-1.5]]) # 1x3 array
diff1 =  A - B - C
print("Diffrence:\n", diff1)



Diffrence:
 [[ 0.  -2.7  0.1]
 [ 4.7  2.   4.8]
 [-0.2 -2.9 -0.1]]


Vector Multiplication

In [7]:
import numpy as np
#Given vector values
A = np.array([[-0.4],[4.3],[-0.6]]) #column vector
B = np.array([[-0.2,0.2,1]]) # 1x2 array
C = np.array([[-0.2,2.1,-1.5]]) # 1x3 array
product= A*B*C
print("Product:\n",product)

Product:
 [[-0.016 -0.168  0.6  ]
 [ 0.172  1.806 -6.45 ]
 [-0.024 -0.252  0.9  ]]


Vector Division

In [10]:
import numpy as np
#Given vector values
A = np.array([[-0.4],[4.3],[-0.6]]) #column vector
B = np.array([[-0.2,0.2,1]]) # 1x2 array
C = np.array([[-0.2,2.1,-1.5]]) # 1x3 array
quotient = A/B/C
print("Quotient:\n", quotient)

Quotient:
 [[-10.          -0.95238095   0.26666667]
 [107.5         10.23809524  -2.86666667]
 [-15.          -1.42857143   0.4       ]]
