<a href="https://colab.research.google.com/github/Darielle-Angela-Valero/58013-Linear-Algebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [ ]:
#Coding Activity 10
import numpy as np
A = np.array([[30, 10, 120],
              [40, 20, 200],
              [50, 40, 360]])
B = np.array([12500, 18000, 25700])

# Solve using NumPy
solution = np.linalg.solve(A, B)

price_of_flour = solution[0]
price_of_yeast = solution[1]
price_per_egg = solution[2]

# Display the results
print("Price per sack of flour in Php:", (price_of_flour) )
print("Price per pack of yeast:", (price_of_yeast))
print("Price per egg:", (price_per_egg))

Price per sack of flour: 330.0
Price per pack of yeast: 139.99999999999986
Price per egg: 10.00000000000002
