<a href="https://colab.research.google.com/github/Darielle-Angela-Valero/58013-Linear-Algebra/blob/main/Vector%2C_Spaces%2C_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#Size Dimension, Size

import numpy as np
ball1=np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1)
balls = np.shape(ball2)
z = ball+balls
print(z)


[1 2 3]
[ 0  1 -1]
(3, 3)


In [21]:
#Addition
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
R = A + B #added x and y axis together
print(R)

[ 6 -2]


In [24]:
#Subtraction
r1 = np.subtract(A,B)
print(r1)
r2 = np.subtract(B,A)
print(r2)

[2 8]
[-2 -8]


In [26]:
#Scalar Product

S = np.array([2])
V = S*A
print(V)

[8 6]


In [42]:
#Dot Product

A = np.array ([4,3])
B = np.array ([[2],[-5]])

print(A*B)


[[  8   6]
 [-20 -15]]


In [54]:
#Property of Matrix

#Identity Matrix
c = np.eye(3,3)
print("\n",c)

#Zero Matrix
d = np.zeros([5,5])
print("\n",d)

#Full Matrix
e = np.full((3,3),7)
print("\n",e)

#Transpose Matrix
f = np.transpose(A)
print("\n",f)

g = np.array([[4,3],[2,-5]])
g.transpose()

#Empty Matrix
c = np.empty([2,2])
print("\n", c)





 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [4 3]

 [[4.94064261e-310 0.00000000e+000]
 [5.73116149e-322 2.56761491e-312]]
